name: Deploy
run-name: Deploying...
on:
  push:
    branches: [main]
jobs:
  deploy-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    env:
      APP_SECRETS: ${{ secrets.APP_SECRETS }}
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      DEPLOY_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Export secrets
        run: echo ${{secrets.APP_SECRETS}} > sshenv
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          source: "sshenv"
          target: "~/.ssh"
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: ./provision.sh
