name: Deploy
run-name: Deploying...
on:
  push:
    branches: [main]
jobs:
  deploy-job:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Export secrets
        run: echo "$APP_SECRETS" > environment
        env:
          APP_SECRETS: ${{ secrets.APP_SECRETS }}
      - name: Update remote environment
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          source: "environment"
          target: ".ssh"
      - name: Copy deploy script
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          source: "./scripts/provision.sh"
          target: "./"
      - name: executing remote script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: "export $(cat ./.ssh/environment | xargs) && ./scripts/provision.sh"
